---
title: "Group 37 UCSB Domestic Grad Enrollment"
author: "German Silva & Tommy King"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Attach packages

library(here)
library(tidyverse)
```

German (Partner 2):
```{r}
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```

Tommy (Partner 1): 
```{r}
# Creating a new geom_col graph to show change in domestic graduate enrollment from 2008-2019

ggplot(data = ucsb_grad, 
       aes(x= year_abbr, y= domestic_enrollment)) +
  geom_col(aes(fill = ethnicity))
```

German (Partner 2):
```{r}
# Updating bar graph to make bars proportional

ggplot(data = ucsb_grad, 
       aes(x= year_abbr, y= domestic_enrollment)) +
  geom_col(aes(fill = ethnicity), position = "fill") +
  labs(x = "Enrollment Year",
       y= "Number of Domestic students")

```

Tommy (Partner 1):
```{r}
# updating the graph, Adding title, setting theme to theme_minimal(), and adding a figure caption

ggplot(data = ucsb_grad, 
       aes(x= year_abbr, y= domestic_enrollment)) +
  geom_col(aes(fill = ethnicity), position = "fill") +
  labs(x = "Enrollment Year",
       y= "Number of Domestic students", 
       title = "Domestic Student Enrollment by Ethnicity per Year", 
       caption = "Figure 1: Domestic Student Enrollment by Ethnicity per year: 
       Column graph depicting the number of domestic students who have enrolled
       at UC Santa Barbara per year from 2008-2019, categorized by Ethnicity. 
       Majority of students enrolled are white, with a growing population of 
       Asian/Pacific Islander students since 2008.") + 
  theme_minimal()+
  theme(plot.caption = element_text(hjust = 0))
```

